[package]
name = "usme"
version = "0.1.0"
edition = "2021"
authors = ["Austin T J <austintjsoft@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A lightweight symbolic math engine for differentiation and simplification."
repository = "https://github.com/tutu0010/usme"
readme = "README.md"
keywords = ["math", "symbolic", "calculus", "differentiation"]
categories = ["science", "mathematics", "parser-implementations"]

[dev-dependencies]
proptest = "1.5.0"
